// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderUpdate.Models;

#nullable disable

namespace order.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230924094958_changeInitialCatalog")]
    partial class changeInitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderUpdate.Models.Orders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("OrderQuantity")
                        .HasColumnType("int");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ordertype")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderUpdate.Models.SubOrders", b =>
                {
                    b.Property<int>("SuborderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuborderID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("SuborderQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Subordertype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuborderID");

                    b.HasIndex("OrderID");

                    b.ToTable("SubOrders");
                });

            modelBuilder.Entity("OrderUpdate.Models.SubOrders", b =>
                {
                    b.HasOne("OrderUpdate.Models.Orders", "Orders")
                        .WithMany("SubOrders")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderUpdate.Models.Orders", b =>
                {
                    b.Navigation("SubOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
